spring:
    application:
      name: Example
    datasource:
      memo-app:
        jdbc-url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
      dashboard-db:
        jdbc-url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DASHBOARD_DB_NAME}?sslmode=disable
        username: ${DASHBOARD_DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
      edusystem-db:
        jdbc-url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${EDUSYSTEM_DB_NAME}?sslmode=disable
        username: ${EDUSYSTEM_DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

#app:
#  admin:
#    password: ${ADMIN_PASSWORD}
#54.206.6.41
#cloud:
#  aws:
#    credentials:
#      access-key: ${AWS_ACCESS_KEY}
#      secret-key: ${AWS_SECRET_KEY}
#    region:
#      static: ap-northeast-2
#    s3:
#      bucket: code-present